# Makefile

run:
	docker compose run --rm alpine echo 'Hello, World!'

help:
	docker compose run --rm alpine sh -c "echo 'Exposed targets:' && echo '  run: run the app' && echo ' help: prints this message'"
