version: "3"
services:
    webserver:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html

    database:
        image: mariadb:10.5.8
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - ./db.env
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USER --password=$$MYSQL_ROOT_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55

    data_load:
        image: mariadb:10.5.8
        volumes:
            - ./seed_database:/seed_database
        env_file:
            - ./db.env
        command: /seed_database/load-schema.sh
        depends_on:
            database:
                condition: service_healthy

    client:
        image: mariadb:10.5.8
        env_file:
            - ./db.env
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: bash

    curl:
        image: curlimages/curl
        volumes:
            - ./test-scripts:/app
        entrypoint: sh
        environment:
            WEB_SERVER_ADDRESS: webserver
        working_dir: /app

    make:
        image: flemay/musketeers
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: make

volumes:
    dbdata:
        external: true
